name: Build LaTeX CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile English CV
        run: |
          pdflatex -interaction=nonstopmode src/cv_english.tex
          bibtex cv_abrv
          pdflatex -interaction=nonstopmode src/cv_english.tex
          pdflatex -interaction=nonstopmode src/cv_english.tex

      - name: Compile French CV
        run: |
          pdflatex -interaction=nonstopmode src/cv_french.tex
          bibtex cv_abrv
          pdflatex -interaction=nonstopmode src/cv_french.tex
          pdflatex -interaction=nonstopmode src/cv_french.tex

      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: cv-pdfs
          path: |
            cv_english.pdf
            cv_french.pdf